
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Mi_TPV_1 extends javax.swing.JFrame {
    
    DefaultTableModel c;

     public Mi_TPV_1() {
        initComponents();
        PrepararTablaCuenta();
        
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            new Mi_TPV_1().setVisible(true);
        }    
        jPanel6Izqda.setPreferredSize(new Dimension(250, jPanel5.getHeight())); 
        jPanel7Dcha.setPreferredSize(new Dimension(300, jPanel5.getHeight())); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6Izqda = new javax.swing.JPanel();
        PanelCategorias = new javax.swing.JPanel();
        jScrollPaneCateg = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelCateg = new javax.swing.JLabel();
        buttonAnadirCateg = new javax.swing.JButton();
        SuprimirCateg = new javax.swing.JButton();
        jPanel8Ctro = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AnadirProduc = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7Dcha = new javax.swing.JPanel();
        PanelPrecios = new javax.swing.JPanel();
        LabelPrecios = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuenta = new javax.swing.JTable();
        sumaCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EliminarFilaProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6Izqda.setBackground(new java.awt.Color(64, 167, 202));

        PanelCategorias.setBackground(new java.awt.Color(64, 167, 202));

        jScrollPaneCateg.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1, 2, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jScrollPaneCateg.setViewportView(jPanel3);

        LabelCateg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCateg.setForeground(new java.awt.Color(255, 255, 255));
        LabelCateg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCateg.setText("CATEGORIAS");

        javax.swing.GroupLayout PanelCategoriasLayout = new javax.swing.GroupLayout(PanelCategorias);
        PanelCategorias.setLayout(PanelCategoriasLayout);
        PanelCategoriasLayout.setHorizontalGroup(
            PanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoriasLayout.createSequentialGroup()
                .addGroup(PanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCategoriasLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPaneCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        PanelCategoriasLayout.setVerticalGroup(
            PanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        buttonAnadirCateg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAnadirCateg.setText("Añadir ");
        buttonAnadirCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnadirCategActionPerformed(evt);
            }
        });

        SuprimirCateg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SuprimirCateg.setText("Suprimir");
        SuprimirCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuprimirCategActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6IzqdaLayout = new javax.swing.GroupLayout(jPanel6Izqda);
        jPanel6Izqda.setLayout(jPanel6IzqdaLayout);
        jPanel6IzqdaLayout.setHorizontalGroup(
            jPanel6IzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6IzqdaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonAnadirCateg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SuprimirCateg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6IzqdaLayout.setVerticalGroup(
            jPanel6IzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6IzqdaLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(PanelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel6IzqdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAnadirCateg)
                    .addComponent(SuprimirCateg))
                .addGap(30, 30, 30))
        );

        jPanel5.add(jPanel6Izqda, java.awt.BorderLayout.LINE_START);

        jPanel8Ctro.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8Ctro.setLayout(new javax.swing.BoxLayout(jPanel8Ctro, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setBackground(new java.awt.Color(255, 149, 0));

        jLabel1.setBackground(new java.awt.Color(255, 149, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTOS");
        jLabel1.setToolTipText("");

        AnadirProduc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AnadirProduc.setText("+");
        AnadirProduc.setToolTipText("");
        AnadirProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnadirProducActionPerformed(evt);
            }
        });

        EliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EliminarProducto.setText("-");
        EliminarProducto.setToolTipText("");
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(EliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnadirProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EliminarProducto)
                    .addComponent(AnadirProduc)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel8Ctro.add(jPanel12);

        jPanel6.setLayout(new java.awt.CardLayout());
        jPanel6.add(jTabbedPane1, "card2");
        jTabbedPane1.getAccessibleContext().setAccessibleName("Bebidas");

        jPanel8Ctro.add(jPanel6);

        jPanel5.add(jPanel8Ctro, java.awt.BorderLayout.CENTER);

        jPanel7Dcha.setBackground(new java.awt.Color(64, 167, 202));
        jPanel7Dcha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrecios.setBackground(new java.awt.Color(64, 167, 202));

        LabelPrecios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelPrecios.setForeground(new java.awt.Color(255, 255, 255));
        LabelPrecios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPrecios.setText("PRECIOS");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tablaCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCuenta);

        sumaCuenta.setToolTipText("");
        sumaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaCuentaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Total Cuenta");

        EliminarFilaProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EliminarFilaProducto.setText("Suprimir");
        EliminarFilaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarFilaProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(EliminarFilaProducto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sumaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(EliminarFilaProducto)
                .addGap(25, 25, 25))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout PanelPreciosLayout = new javax.swing.GroupLayout(PanelPrecios);
        PanelPrecios.setLayout(PanelPreciosLayout);
        PanelPreciosLayout.setHorizontalGroup(
            PanelPreciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelPrecios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelPreciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPreciosLayout.setVerticalGroup(
            PanelPreciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPreciosLayout.createSequentialGroup()
                .addComponent(LabelPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7Dcha.add(PanelPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 510));

        jPanel5.add(jPanel7Dcha, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel5, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PrepararTablaCuenta(){
        String titulos[] = {"Nombre", "Cantidad", "Precio"};
        c = new DefaultTableModel(null, titulos);
        tablaCuenta.setModel(c);
    }
    
    //BOTON AÑADIR CATEGORIA
    private void buttonAnadirCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnadirCategActionPerformed
        NuevaCategoria_1 ncat = new NuevaCategoria_1(this, true);
        ncat.setVisible(true);

        //Obtengo el nombre de la categoría del cuadro de diálogo
        String nombreCategoria = ncat.jTextFieldNuevaCateg.getText();

        //Compruebo si se introce un nombre correcto
        if (nombreCategoria != null && !nombreCategoria.isEmpty()) {
            //Llama al método agregarCategoria para agregar la nueva categoría
            agregarCategoria(nombreCategoria);
        } else {
            //Muestro un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, introduzca un nombre válido para la categoría", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_buttonAnadirCategActionPerformed
    
    public static ArrayList<String> NombresCategorias = new ArrayList(); 
    public static ArrayList<PanelProductos_1> listaPaneles =  new ArrayList();
        
    private void agregarCategoria(String nombreCategoria) {
        // Creo la nueva pestaña con el nombre de la categoría
        PanelProductos_1 PanelProductos = new PanelProductos_1();
        listaPaneles.add(PanelProductos);
        jTabbedPane1.addTab(nombreCategoria, PanelProductos);

        // Modifica el color de fondo de la pestaña
        int indicePestana = jTabbedPane1.indexOfTab(nombreCategoria);
        if (indicePestana != -1) {
            JPanel tabPanel = new JPanel();
            tabPanel.setBackground(new Color(255, 149, 0));
            JLabel tabLabel = new JLabel(nombreCategoria);
            tabPanel.add(tabLabel);
            tabPanel.setOpaque(true);
            jTabbedPane1.setTabComponentAt(indicePestana, tabPanel);
        }

        // Creo un nuevo botón con el nombre de la categoría y el fondo en el color naranja
        JButton btnNuevaCateg = new JButton("<html><b>" + nombreCategoria + "</b></html>");
        btnNuevaCateg.setPreferredSize(new Dimension(80, 50));
        btnNuevaCateg.setBackground(new Color(255, 149, 0));

        jPanel4.add(btnNuevaCateg);
        NombresCategorias.add(nombreCategoria);

        // Evento para cambiar a la pestaña correspondiente desde la categoría
        btnNuevaCateg.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtengo el índice de la pestaña según el nombre de la categoría
                int indicePestana = jTabbedPane1.indexOfTab(nombreCategoria);

                // Cambio a la pestaña correspondiente
                if (indicePestana != -1) {
                    jTabbedPane1.setSelectedIndex(indicePestana);
                }
            }
        });

        // Actualiza la interfaz
        jPanel4.revalidate();
        jPanel4.repaint();
    }  
        
    //AÑADIR PRODUCTO
    private void AnadirProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnadirProducActionPerformed
        NuevoProducto_1 npto = new NuevoProducto_1(Mi_TPV_1.this, true);
        npto.setVisible(true);         
    }//GEN-LAST:event_AnadirProducActionPerformed

    //ELIMINAR PRODUCTO
    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        

    }//GEN-LAST:event_EliminarProductoActionPerformed
     
    //BOTON PARA MOSTRAR LA SUMA DE LA CUENTA
    private void sumaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaCuentaActionPerformed
        // Llamo al método para calcular la suma total
        double sumaTotal = calcularSumaTotal();
        // Actualizo el campo de texto con la nueva suma total
        sumaCuenta.setText(String.valueOf(sumaTotal));
    }//GEN-LAST:event_sumaCuentaActionPerformed
    // Calculo de la suma
    // Método que calcula la suma total de los precios en la tabla de la cuenta
    public static double calcularSumaTotal() {
        // Obtengo el modelo de la tabla de la cuenta
        DefaultTableModel modeloTabla = (DefaultTableModel) Mi_TPV_1.tablaCuenta.getModel();
        // Inicializo la variable para almacenar la suma total
        double sumaTotal = 0;
        // Recorro las filas de la tabla
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            // Obtengo el precio de la fila actual
            double precio = (double) modeloTabla.getValueAt(i, 2);
            // Agrego el precio al total
            sumaTotal += precio;
        }
        // Devuelvo la suma total calculada
        return sumaTotal;
    }
    
    //BOTON ELIMINAR FILA
    private void EliminarFilaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarFilaProductoActionPerformed
        //Obtengo la fila seleccionada
        int filaSeleccionada = Mi_TPV_1.tablaCuenta.getSelectedRow();

        //Compruebo si hay una fila seleccionada
        if (filaSeleccionada == -1) {
            //No hay fila seleccionada, muestro un mensaje de advertencia
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fila para eliminar.",
                    "Eliminar", JOptionPane.WARNING_MESSAGE);
        } else {
            //Si hay una fila seleccionada, solicito confirmacion para eliminar
            int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar esta fila?",
                    "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
                    //Si el usuario selecciona "No" se cierra el dialogo
            //Si el usuario confirma la eliminacion, elimino la fila
            if (opcion == JOptionPane.YES_OPTION) {                
                DefaultTableModel modeloTabla = (DefaultTableModel) Mi_TPV_1.tablaCuenta.getModel();
                modeloTabla.removeRow(filaSeleccionada);
            }            
        }
        
        //Actualizar la suma despues de eliminar una fila de la cuenta
        double nuevaSuma = Mi_TPV_1.calcularSumaTotal();
        Mi_TPV_1.sumaCuenta.setText(String.valueOf(nuevaSuma));
    }//GEN-LAST:event_EliminarFilaProductoActionPerformed
   
    //BOTON SUPRIMIR CATEGORIA
    private void SuprimirCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuprimirCategActionPerformed
        // Variable para almacenar la decision sobre la eliminacion de la categoria
        int opcionEliminar;

        // Bucle para permitir eliminar varias categorias 
        do {
            // Obtengo el índice de la pestaña que he seleccionado en el panel de pestañas
            int indicePestana = jTabbedPane1.getSelectedIndex();

            // Compruebo si he seleccionado alguna categoría
            if (indicePestana != -1) {
                // Obtengo el nombre de la categoría que he seleccionado
                String nombreCategoria = jTabbedPane1.getTitleAt(indicePestana);

                //confirmo si quiero eliminar la categoría con un msje
                opcionEliminar = JOptionPane.showConfirmDialog(this,
                        "¿Estoy seguro de que quiero eliminar la categoría \"" + nombreCategoria + "\"?",
                        "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);

                // Si confirmo la eliminación, procedo a eliminar la categoría
                if (opcionEliminar == JOptionPane.YES_OPTION) {
                    // Elimino la pestaña correspondiente al índice
                    jTabbedPane1.removeTabAt(indicePestana);

                    // Elimino el botón de la categoría en el panel de categorías
                    if (indicePestana < jPanel4.getComponentCount()) {
                        jPanel4.remove(indicePestana);
                        jPanel4.revalidate();
                        jPanel4.repaint();
                    }

                    // Elimino el nombre de la categoría de mi lista de nombres de categorías
                    if (indicePestana < NombresCategorias.size()) {
                        NombresCategorias.remove(indicePestana);
                    }
                }
            } else {
                // Muestro un mensaje si no he seleccionado ninguna categoría
                JOptionPane.showMessageDialog(this, "Por favor, selecciona una categoría para eliminar.",
                        "Eliminar Categoría", JOptionPane.WARNING_MESSAGE);
            }

            //Pregunto si quiero eliminar otra categoría
            opcionEliminar = JOptionPane.showConfirmDialog(this,
                    "¿Quiero eliminar otra categoría?", "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION);

        } while (opcionEliminar == JOptionPane.YES_OPTION);
    }//GEN-LAST:event_SuprimirCategActionPerformed
    
    //AGREGAR PRODUCTO A TABLA
    public void agregarProductoATabla(String nombre, int cantidad, double precioUnitario) {
        DefaultTableModel modelo = (DefaultTableModel) tablaCuenta.getModel();
        boolean productoExistente = false;
        int filaExistente = -1;

        //si el producto ya existe en la tabla
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombreExistente = (String) modelo.getValueAt(i, 0);
            if (nombreExistente.equals(nombre)) {
                productoExistente = true;
                filaExistente = i;
                break;
            }
        }
        //Si el producto ya existe, actualizo cantidad y precio
        if (productoExistente) {
            int cantidadExistente = (int) modelo.getValueAt(filaExistente, 1);
            double precioExistente = (double) modelo.getValueAt(filaExistente, 2);
            cantidadExistente++;
            precioExistente += precioUnitario;

            modelo.setValueAt(cantidadExistente, filaExistente, 1);
            modelo.setValueAt(precioExistente, filaExistente, 2);
        } else {
            //Si el producto no existe, agrego una nueva fila
            Object[] fila = {nombre, 1, precioUnitario};
            modelo.addRow(fila);
        }
    }
    
    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirProduc;
    private javax.swing.JButton EliminarFilaProducto;
    private javax.swing.JButton EliminarProducto;
    private javax.swing.JLabel LabelCateg;
    private javax.swing.JLabel LabelPrecios;
    private javax.swing.JPanel PanelCategorias;
    private javax.swing.JPanel PanelPrecios;
    private javax.swing.JButton SuprimirCateg;
    private javax.swing.JButton buttonAnadirCateg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel6Izqda;
    private javax.swing.JPanel jPanel7Dcha;
    private javax.swing.JPanel jPanel8Ctro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneCateg;
    public static javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField sumaCuenta;
    public static javax.swing.JTable tablaCuenta;
    // End of variables declaration//GEN-END:variables
}
